    
FROM microsoft/dotnet:2.2-sdk-alpine AS build-env

WORKDIR /.
COPY /. /build

WORKDIR /build
RUN dotnet publish -c Release -o ../app

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine

WORKDIR /app
COPY --from=build-env /app .

ENTRYPOINT ["dotnet", "teste.dll"]
