// <auto-generated />
using System;
using DeOlho.Services.Politicos.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.Services.Politicos.Api.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    [Migration("20190529005830_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.Services.Politicos.Api.Domain.Legislatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<string>("IntegrationOrigin");

                    b.Property<long>("IntegrationTimestamp");

                    b.HasKey("Id");

                    b.ToTable("Legislaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
