// <auto-generated />
using System;
using DeOlho.ETL.dadosabertos_leg_br.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.ETL.dadosabertos_leg_br.Infrastructure.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    [Migration("20190618021703_ajuste_notafiscal")]
    partial class ajuste_notafiscal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_leg_br.Domain.DeputadoFederal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<string>("CondicaoEleitoral");

                    b.Property<string>("GabineteAndar");

                    b.Property<string>("GabineteEmail");

                    b.Property<string>("GabineteNome");

                    b.Property<string>("GabinetePredio");

                    b.Property<string>("GabineteSala");

                    b.Property<string>("GabineteTelefone");

                    b.Property<long>("OrigemId");

                    b.Property<string>("URLFoto");

                    b.Property<string>("URLWebsite");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("OrigemId")
                        .IsUnique();

                    b.ToTable("DeputadoFederal");
                });

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_leg_br.Domain.NotaFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<long>("CPF");

                    b.Property<string>("CnpjCpfFornecedor");

                    b.Property<long>("CodDocumento");

                    b.Property<long>("CodLote");

                    b.Property<int?>("CodTipoDocumento");

                    b.Property<DateTime?>("DataDocumento");

                    b.Property<long>("DeputadoFederalOrigemId");

                    b.Property<int>("Mes");

                    b.Property<string>("NomeFornecedor");

                    b.Property<string>("NumDocumento");

                    b.Property<string>("NumRessarcimento");

                    b.Property<int>("Parcela");

                    b.Property<string>("TipoDespesa");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("URLDocumento");

                    b.Property<decimal>("ValorDocumento");

                    b.Property<decimal>("ValorGlosa");

                    b.Property<decimal>("ValorLiquido");

                    b.HasKey("Id");

                    b.HasIndex("CodDocumento")
                        .IsUnique();

                    b.ToTable("NotaFiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
