// <auto-generated />
using System;
using DeOlho.ETL.dadosabertos_camara_leg_br.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.ETL.dadosabertos_camara_leg_br.Api.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    [Migration("20190531013257_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_camara_leg_br.Api.Domain.Despesa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("CnpjCpfFornecedor");

                    b.Property<long>("CodDocumento");

                    b.Property<long>("CodLote");

                    b.Property<int?>("CodTipoDocumento");

                    b.Property<DateTime?>("DataDocumento");

                    b.Property<long>("DeputadoId");

                    b.Property<int>("Mes");

                    b.Property<string>("NomeFornecedor");

                    b.Property<string>("NumDocumento");

                    b.Property<string>("NumRessarcimento");

                    b.Property<int>("Parcela");

                    b.Property<string>("TipoDespesa");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("URLDocumento");

                    b.Property<decimal>("ValorDocumento");

                    b.Property<decimal>("ValorGlosa");

                    b.Property<decimal>("ValorLiquido");

                    b.HasKey("Id");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_camara_leg_br.Api.Domain.Legislatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.HasKey("Id");

                    b.ToTable("Legislaturas");
                });

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_camara_leg_br.Api.Domain.Partido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Data");

                    b.Property<long>("LegislaturaId");

                    b.Property<string>("LiderId");

                    b.Property<string>("Nome");

                    b.Property<string>("Sigla");

                    b.Property<string>("Situacao");

                    b.Property<int>("TotalMembros");

                    b.Property<int>("TotalPosse");

                    b.Property<string>("UrlFacebook");

                    b.Property<string>("UrlLogo");

                    b.Property<string>("UrlWebSite");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_camara_leg_br.Api.Domain.Politico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("CondicaoEleitoral");

                    b.Property<DateTime?>("Data");

                    b.Property<DateTime?>("DataFalecimento");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("DescricaoStatus");

                    b.Property<string>("Escolaridade");

                    b.Property<string>("GabineteAndar");

                    b.Property<string>("GabineteEmail");

                    b.Property<string>("GabineteNome");

                    b.Property<string>("GabinetePredio");

                    b.Property<string>("GabineteSala");

                    b.Property<string>("GabineteTelefone");

                    b.Property<long>("LegislaturaId");

                    b.Property<string>("MunicipioNascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeCivil");

                    b.Property<string>("NomeEleitoral");

                    b.Property<long>("PartidoId");

                    b.Property<string>("RedeSocial");

                    b.Property<string>("Sexo");

                    b.Property<string>("SiglaPartido");

                    b.Property<string>("SiglaUf");

                    b.Property<string>("Situacao");

                    b.Property<string>("UFNascimento");

                    b.Property<string>("URLFoto");

                    b.Property<string>("URLWebsite");

                    b.HasKey("Id");

                    b.ToTable("Politicos");
                });
#pragma warning restore 612, 618
        }
    }
}
