// <auto-generated />
using System;
using DeOlho.ETL.dadosabertos_camara_leg_br.Api.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.ETL.dadosabertos_camara_leg_br.Api.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    [Migration("20190527235109_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.ETL.dadosabertos_camara_leg_br.Api.Domains.Legislatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.HasKey("Id");

                    b.ToTable("Legislaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
