version: '2.1'
 
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      "RABBITMQ_DEFAULT_USER": "deolho"
      "RABBITMQ_DEFAULT_PASS": "deolho"

  mysql-scheduler:
    image: deolho/mysql-scheduler
    ports:
      - "13306:3306"

  api-scheduler:
    depends_on:
      mysql-scheduler:
        condition: service_healthy
    image: deolho/api-scheduler
    ports:
      - "8081:80"
    environment:
      "scheduler__configuration__connectionstring": "server=mysql-scheduler;Port=3306;uid=root;pwd=deolho;database=db;Allow User Variables=True"
      "RawRabbit__Configuration__Username": "deolho"
      "RawRabbit__Configuration__Password": "deolho"
      "RawRabbit__Configuration__Port": 5672
      "RawRabbit__Configuration__Hostnames": "rabbitmq"



  mysql-dadosabertos_camara_leg_br:
    image: deolho/mysql-dadosabertos_camara_leg_br
    ports:
      - "23306:3306"

  api-dadosabertos_camara_leg_br:
    depends_on:
      mysql-dadosabertos_camara_leg_br:
        condition: service_healthy
    image: deolho/api-dadosabertos_camara_leg_br
    ports:
      - "8082:80"
    environment:
      "ETL__Configuration__ConnectionString": "server=mysql-dadosabertos_camara_leg_br;Port=3306;uid=root;pwd=deolho;database=db;Allow User Variables=True"
      "RawRabbit__Configuration__Username": "deolho"
      "RawRabbit__Configuration__Password": "deolho"
      "RawRabbit__Configuration__Port": 5672
      "RawRabbit__Configuration__Hostnames": "rabbitmq"




#docker run -d --hostname rabbitmq --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=deolho -e RABBITMQ_DEFAULT_PASS=deolho rabbitmq:3-management