// <auto-generated />
using System;
using DeOlho.ETL.camara_leg_br.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.ETL.camara_leg_br.Infrastructure.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    partial class DeOlhoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.ETL.camara_leg_br.Domain.DeputadoFederal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<string>("CondicaoEleitoral");

                    b.Property<string>("GabineteAndar");

                    b.Property<string>("GabineteEmail");

                    b.Property<string>("GabineteNome");

                    b.Property<string>("GabinetePredio");

                    b.Property<string>("GabineteSala");

                    b.Property<string>("GabineteTelefone");

                    b.Property<long>("OrigemId");

                    b.Property<string>("URLFoto");

                    b.Property<string>("URLWebsite");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("OrigemId")
                        .IsUnique();

                    b.ToTable("DeputadoFederal");
                });

            modelBuilder.Entity("DeOlho.ETL.camara_leg_br.Domain.NotaFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<string>("CnpjCpfFornecedor");

                    b.Property<long>("CodDocumento");

                    b.Property<long>("CodLote");

                    b.Property<int>("CodTipoDocumento");

                    b.Property<DateTime>("DataDocumento");

                    b.Property<string>("NomeFornecedor");

                    b.Property<string>("NumDocumento");

                    b.Property<string>("NumRessarcimento");

                    b.Property<int>("Parcela");

                    b.Property<long>("PeriodoId");

                    b.Property<string>("TipoDespesa");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("URLDocumento");

                    b.Property<decimal>("ValorDocumento");

                    b.Property<decimal>("ValorGlosa");

                    b.Property<decimal>("ValorLiquido");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("CodDocumento", "CnpjCpfFornecedor", "CodTipoDocumento", "DataDocumento", "NumDocumento")
                        .IsUnique();

                    b.ToTable("NotaFiscal");
                });

            modelBuilder.Entity("DeOlho.ETL.camara_leg_br.Domain.NotaFiscalPeriodo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<long>("DeputadoFederalId");

                    b.Property<int>("Mes");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoFederalId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("NotaFiscalPeriodo");
                });

            modelBuilder.Entity("DeOlho.ETL.camara_leg_br.Domain.NotaFiscal", b =>
                {
                    b.HasOne("DeOlho.ETL.camara_leg_br.Domain.NotaFiscalPeriodo", "Periodo")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DeOlho.ETL.camara_leg_br.Domain.NotaFiscalPeriodo", b =>
                {
                    b.HasOne("DeOlho.ETL.camara_leg_br.Domain.DeputadoFederal", "DeputadoFederal")
                        .WithMany("NotasFiscaisPeriodos")
                        .HasForeignKey("DeputadoFederalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
