using System;

namespace DeOlho.ETL.tse_jus_br.Api.Domain
{
    public class PoliticoFactory
    {
        public Politico Transform(dynamic _)
        {
            return new Politico (
                DateTime.Parse(_.DT_GERACAO),
                DateTime.Parse(_.HH_GERACAO),
                int.Parse(_.ANO_ELEICAO),
                int.Parse(_.CD_TIPO_ELEICAO),
                _.NM_TIPO_ELEICAO,
                int.Parse(_.NR_TURNO),
                int.Parse(_.CD_ELEICAO),
                _.DS_ELEICAO,
                DateTime.Parse(_.DT_ELEICAO),
                _.TP_ABRANGENCIA,
                _.SG_UF,
                _.SG_UE,
                _.NM_UE,
                int.Parse(_.CD_CARGO),
                _.DS_CARGO,
                long.Parse(_.SQ_CANDIDATO),
                int.Parse(_.NR_CANDIDATO),
                _.NM_CANDIDATO,
                _.NM_URNA_CANDIDATO,
                _.NM_SOCIAL_CANDIDATO,
                long.Parse(_.NR_CPF_CANDIDATO),
                _.NM_EMAIL,
                int.Parse(_.CD_SITUACAO_CANDIDATURA),
                _.DS_SITUACAO_CANDIDATURA,
                int.Parse(_.CD_DETALHE_SITUACAO_CAND),
                _.DS_DETALHE_SITUACAO_CAND,
                _.TP_AGREMIACAO,
                int.Parse(_.NR_PARTIDO),
                _.SG_PARTIDO,
                _.NM_PARTIDO,
                long.Parse(_.SQ_COLIGACAO),
                _.NM_COLIGACAO,
                _.DS_COMPOSICAO_COLIGACAO,
                int.Parse(_.CD_NACIONALIDADE),
                _.DS_NACIONALIDADE,
                _.SG_UF_NASCIMENTO,
                int.Parse(_.CD_MUNICIPIO_NASCIMENTO),
                _.NM_MUNICIPIO_NASCIMENTO,
                DateTime.Parse(_.DT_NASCIMENTO),
                int.Parse(_.NR_IDADE_DATA_POSSE),
                long.Parse(_.NR_TITULO_ELEITORAL_CANDIDATO),
                int.Parse(_.CD_GENERO),
                _.DS_GENERO,
                int.Parse(_.CD_GRAU_INSTRUCAO),
                _.DS_GRAU_INSTRUCAO,
                int.Parse(_.CD_ESTADO_CIVIL),
                _.DS_ESTADO_CIVIL,
                int.Parse(_.CD_COR_RACA),
                _.DS_COR_RACA,
                int.Parse(_.CD_OCUPACAO),
                _.DS_OCUPACAO,
                int.Parse(_.NR_DESPESA_MAX_CAMPANHA),
                int.Parse(_.CD_SIT_TOT_TURNO),
                _.DS_SIT_TOT_TURNO,
                _.ST_REELEICAO,
                _.ST_DECLARAR_BENS,
                int.Parse(_.NR_PROTOCOLO_CANDIDATURA),
                long.Parse(_.NR_PROCESSO)
            );
        }
    }
}